name: Send Newsletter

on:
  schedule:
    - cron: '0 12 * * 1' # This will run the workflow every Monday at 12pm UTC
  workflow_dispatch: # This allows you to manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Send newsletter
      run: npx ts-node ./src/app/newsletter/sendNewsletter.tsx
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}
